//! The build-script half: turn a `skills/` directory into two files in `OUT_DIR`.
//!
//! An engine ships as a single executable, so a skill that only exists in the
//! repository is a skill nobody who installed the engine can reach. This walks
//! the directory, validates each skill's frontmatter, and writes the archive
//! plus a metadata table the binary `include!`s.
//!
//! Nothing here is behind the `runtime` feature, so a build script can take
//! this crate with `default-features = false` and compile flate2 for the host
//! and nothing else. A build script has no business linking an MCP server
//! library to read some Markdown.

use std::fs;
use std::path::{Path, PathBuf};

use crate::archive;

/// Pack `<root>/skills` into `OUT_DIR`, and tell cargo when to do it again.
///
/// Writes `skills.bin` (the archive) and `skills_meta.rs` (a `&[SkillMeta]`
/// expression). Both are generated from **one walk of one directory**, which is
/// what lets the reader treat a count mismatch as "these came from different
/// builds" rather than as a possibility it has to handle.
///
/// A missing `skills/` is not an error: an engine that ships no skills still
/// gets a well-formed empty archive, so `skills list` prints nothing instead of
/// failing.
pub fn pack(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(
        std::env::var_os("OUT_DIR").ok_or("OUT_DIR is set by cargo for every build script")?,
    );
    pack_into(root, &out_dir)
}

/// [`pack`] with an explicit destination, so it can be tested off a build.
pub fn pack_into(root: &Path, out_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let dir = root.join("skills");
    println!("cargo::rerun-if-changed={}", dir.display());

    let mut skills = Vec::new();
    if dir.is_dir() {
        let mut names: Vec<PathBuf> = fs::read_dir(&dir)?
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.is_dir() && !is_hidden(p))
            .collect();
        // Sorted so the blob and the metadata table are byte-identical across
        // machines; `read_dir` order is whatever the filesystem feels like.
        names.sort();
        for name in &names {
            skills.push(SkillSource::read(&dir, name)?);
        }
    }

    let entries: Vec<(String, Vec<u8>)> = skills
        .iter()
        .flat_map(|skill| skill.files.iter().cloned())
        .collect();
    fs::write(out_dir.join("skills.bin"), archive::write(&entries)?)?;

    let mut meta = String::from("// @generated by vibrev-skills from `skills/`. Do not edit.\n");
    meta.push_str("&[\n");
    for skill in &skills {
        meta.push_str(&format!(
            "    ::vibrev_skills::SkillMeta {{ name: {:?}, description: {:?}, files: {}, \
             bytes: {}, fingerprint: {:?} }},\n",
            skill.name,
            skill.description,
            skill.files.len(),
            skill.bytes,
            format!("{:016x}", skill.fingerprint),
        ));
    }
    meta.push_str("]\n");
    fs::write(out_dir.join("skills_meta.rs"), meta)?;

    Ok(())
}

/// One skill directory, read and validated.
struct SkillSource {
    name: String,
    description: String,
    /// `(path relative to `skills/`, contents)`, sorted. The path always uses
    /// `/`, so a Windows build produces the same archive as a Unix one.
    files: Vec<(String, Vec<u8>)>,
    bytes: usize,
    fingerprint: u64,
}

impl SkillSource {
    fn read(base: &Path, dir: &Path) -> Result<Self, Box<dyn std::error::Error>> {
        let name = dir
            .file_name()
            .and_then(|n| n.to_str())
            .ok_or_else(|| format!("skill directory name is not UTF-8: {}", dir.display()))?
            .to_owned();

        let mut files = Vec::new();
        collect_files(base, dir, &mut files)?;
        files.sort();

        let manifest = format!("{name}/SKILL.md");
        let body = files
            .iter()
            .find(|(path, _)| *path == manifest)
            .map(|(_, body)| body)
            .ok_or_else(|| format!("skill '{name}' has no SKILL.md"))?;
        let text =
            std::str::from_utf8(body).map_err(|e| format!("{manifest} is not valid UTF-8: {e}"))?;

        let declared = frontmatter_field(text, "name")
            .ok_or_else(|| format!("{manifest} frontmatter has no `name:`"))?;
        if declared != name {
            // A skill is addressed by directory name once it is exported, so a
            // frontmatter that disagrees would make `skills list` describe one
            // thing and `skills export` write another.
            return Err(format!(
                "{manifest} declares name '{declared}' but sits in directory '{name}'"
            )
            .into());
        }
        let description = frontmatter_field(text, "description")
            .ok_or_else(|| format!("{manifest} frontmatter has no `description:`"))?;
        if description.is_empty() {
            return Err(format!("{manifest} has an empty `description:`").into());
        }

        let bytes = files.iter().map(|(_, body)| body.len()).sum();
        let fingerprint = archive::fingerprint(&files);

        Ok(Self {
            name,
            description,
            files,
            bytes,
            fingerprint,
        })
    }
}

fn collect_files(
    base: &Path,
    dir: &Path,
    out: &mut Vec<(String, Vec<u8>)>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        // `.DS_Store` and friends are not part of the skill, and shipping one
        // would change the fingerprint depending on who built the binary.
        if is_hidden(&path) {
            continue;
        }
        if path.is_dir() {
            collect_files(base, &path, out)?;
            continue;
        }
        let rel = path
            .strip_prefix(base)?
            .to_str()
            .ok_or_else(|| format!("skill file path is not UTF-8: {}", path.display()))?
            .replace('\\', "/");
        out.push((rel, fs::read(&path)?));
    }
    Ok(())
}

/// Pull one `key: value` line out of a SKILL.md YAML frontmatter block.
///
/// Not a YAML parser: the two fields we need are single-line scalars, and a
/// build script that pulls in a YAML crate to read two strings pays a lot for
/// very little. Anything that is not a plain scalar — a folded (`>`) or literal
/// (`|`) block — returns `None` and surfaces as "no such field" rather than as a
/// silently truncated description.
fn frontmatter_field(text: &str, key: &str) -> Option<String> {
    let body = text.strip_prefix("---\n")?;
    let end = body.find("\n---")?;
    let raw = body[..end].lines().find_map(|line| {
        let value = line.strip_prefix(key)?.strip_prefix(':')?.trim();
        Some(value)
    })?;
    if raw.starts_with(['>', '|']) {
        return None;
    }
    let unquoted = raw
        .strip_prefix('"')
        .and_then(|s| s.strip_suffix('"'))
        .or_else(|| raw.strip_prefix('\'').and_then(|s| s.strip_suffix('\'')))
        .unwrap_or(raw);
    Some(unquoted.to_owned())
}

fn is_hidden(path: &Path) -> bool {
    path.file_name()
        .and_then(|n| n.to_str())
        .is_some_and(|n| n.starts_with('.'))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("vibrev-skills-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("scratch");
        dir
    }

    fn write_skill(root: &Path, name: &str, frontmatter: &str, extra: &[(&str, &str)]) {
        let dir = root.join("skills").join(name);
        fs::create_dir_all(&dir).expect("skill dir");
        fs::write(dir.join("SKILL.md"), frontmatter).expect("SKILL.md");
        for (rel, body) in extra {
            let path = dir.join(rel);
            fs::create_dir_all(path.parent().expect("parent")).expect("nested dir");
            fs::write(path, body).expect("extra file");
        }
    }

    fn good(name: &str) -> String {
        format!("---\nname: {name}\ndescription: does a thing\n---\n\n# {name}\n")
    }

    #[test]
    fn a_packed_skill_round_trips_through_the_metadata_table() {
        let root = scratch("pack-ok");
        write_skill(&root, "alpha", &good("alpha"), &[("docs/a.md", "aaa")]);
        let out = root.join("out");
        fs::create_dir_all(&out).expect("out");

        pack_into(&root, &out).expect("pack");

        let meta = fs::read_to_string(out.join("skills_meta.rs")).expect("meta");
        assert!(meta.contains("name: \"alpha\""), "{meta}");
        assert!(meta.contains("description: \"does a thing\""), "{meta}");
        assert!(meta.contains("files: 2"), "{meta}");
        // A whole fingerprint, not a truncated one.
        let fingerprint = meta
            .split("fingerprint: \"")
            .nth(1)
            .and_then(|s| s.split('"').next())
            .expect("fingerprint in the table");
        assert_eq!(fingerprint.len(), 16);

        let entries = archive::read(&fs::read(out.join("skills.bin")).expect("bin")).expect("read");
        assert_eq!(entries.len(), 2);
        assert!(entries.iter().any(|(p, _)| p == "alpha/docs/a.md"));
    }

    /// The build fails rather than shipping a skill whose directory and
    /// frontmatter name different things — `skills list` would describe one and
    /// `skills export` would write the other.
    #[test]
    fn a_frontmatter_name_that_disagrees_with_the_directory_fails_the_build() {
        let root = scratch("pack-mismatch");
        write_skill(&root, "alpha", &good("beta"), &[]);
        let out = root.join("out");
        fs::create_dir_all(&out).expect("out");

        let err = pack_into(&root, &out).expect_err("must fail");
        let message = err.to_string();
        assert!(message.contains("alpha"), "{message}");
        assert!(message.contains("beta"), "{message}");
    }

    #[test]
    fn a_skill_without_a_manifest_or_a_description_fails_the_build() {
        let root = scratch("pack-nomanifest");
        let dir = root.join("skills").join("alpha");
        fs::create_dir_all(&dir).expect("dir");
        fs::write(dir.join("notes.md"), "hi").expect("write");
        let out = root.join("out");
        fs::create_dir_all(&out).expect("out");
        assert!(pack_into(&root, &out).is_err(), "no SKILL.md must fail");

        let root = scratch("pack-nodesc");
        write_skill(&root, "alpha", "---\nname: alpha\ndescription:\n---\n", &[]);
        let out = root.join("out");
        fs::create_dir_all(&out).expect("out");
        assert!(pack_into(&root, &out).is_err(), "empty description");
    }

    /// A repository with no `skills/` still has to build. Producing an empty
    /// archive here is what lets every engine carry the same subcommand.
    #[test]
    fn no_skills_directory_produces_a_well_formed_empty_archive() {
        let root = scratch("pack-none");
        let out = root.join("out");
        fs::create_dir_all(&out).expect("out");

        pack_into(&root, &out).expect("pack");
        assert_eq!(
            fs::read_to_string(out.join("skills_meta.rs"))
                .expect("meta")
                .matches("SkillMeta")
                .count(),
            0
        );
        assert!(
            archive::read(&fs::read(out.join("skills.bin")).expect("bin"))
                .expect("read")
                .is_empty()
        );
    }

    /// Two builds of the same tree produce the same bytes, whatever order the
    /// filesystem hands the entries back in. The fingerprint is what an
    /// installer compares to decide "already up to date"; if it moved between
    /// machines, every install would look stale.
    #[test]
    fn packing_is_reproducible_and_ignores_dotfiles() {
        let root = scratch("pack-repro");
        write_skill(
            &root,
            "alpha",
            &good("alpha"),
            &[("docs/z.md", "z"), ("docs/a.md", "a")],
        );
        write_skill(&root, "beta", &good("beta"), &[]);
        fs::write(root.join("skills/alpha/.DS_Store"), "junk").expect("dotfile");

        let first = root.join("out1");
        let second = root.join("out2");
        fs::create_dir_all(&first).expect("out1");
        fs::create_dir_all(&second).expect("out2");
        pack_into(&root, &first).expect("pack");
        pack_into(&root, &second).expect("pack");

        assert_eq!(
            fs::read(first.join("skills.bin")).expect("bin"),
            fs::read(second.join("skills.bin")).expect("bin")
        );
        assert_eq!(
            fs::read_to_string(first.join("skills_meta.rs")).expect("meta"),
            fs::read_to_string(second.join("skills_meta.rs")).expect("meta")
        );

        let meta = fs::read_to_string(first.join("skills_meta.rs")).expect("meta");
        assert!(
            meta.find("\"alpha\"") < meta.find("\"beta\""),
            "skills are listed in sorted order: {meta}"
        );
        assert!(
            !archive::read(&fs::read(first.join("skills.bin")).expect("bin"))
                .expect("read")
                .iter()
                .any(|(path, _)| path.contains(".DS_Store")),
            "a dotfile would make the fingerprint depend on who built the binary"
        );
    }

    #[test]
    fn frontmatter_reads_scalars_and_declines_blocks() {
        let text = "---\nname: alpha\ndescription: \"quoted\"\nother: 'single'\n---\nbody";
        assert_eq!(frontmatter_field(text, "name").as_deref(), Some("alpha"));
        assert_eq!(
            frontmatter_field(text, "description").as_deref(),
            Some("quoted")
        );
        assert_eq!(frontmatter_field(text, "other").as_deref(), Some("single"));
        assert_eq!(frontmatter_field(text, "missing"), None);

        // A folded block reads as absent rather than as its first line, so it
        // fails the build instead of shipping a truncated description.
        let folded = "---\nname: alpha\ndescription: >\n  long text\n---\nbody";
        assert_eq!(frontmatter_field(folded, "description"), None);

        assert_eq!(frontmatter_field("no frontmatter here", "name"), None);
    }
}
